DROP TABLE IF EXISTS car_rental;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS car;
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS extra_features;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS user;


